general.import = [
    # "~/.config/alacritty/dracula.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
	TERM = "xterm-256color"
[font]
	normal = { family = "JetBrainsMono NerdFont", style = "Regular" }
[terminal]
	shell = "fish"

